[package]
name = "tauri-app"
version = "0.0.0"
publish = false
edition = "2021"

[build-dependencies]
tauri-build = "2.0.0-beta"

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
tauri-plugin-drag = { path = "../../crates/tauri-plugin-drag/" }
